package com.aires.model;

// Generated Jul 23, 2014 1:40:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SampleTypes generated by hbm2java
 */
@Entity
@Table(name = "SampleTypes", schema = "dbo", catalog = "MOBILE_AirQuality")
public class SampleTypes implements java.io.Serializable {

	private int sampleTypeId;
	private String sampleTypeName;
	private Set<Samples> sampleses = new HashSet<Samples>(0);

	public SampleTypes() {
	}

	public SampleTypes(int sampleTypeId, String sampleTypeName) {
		this.sampleTypeId = sampleTypeId;
		this.sampleTypeName = sampleTypeName;
	}

	public SampleTypes(int sampleTypeId, String sampleTypeName,
			Set<Samples> sampleses) {
		this.sampleTypeId = sampleTypeId;
		this.sampleTypeName = sampleTypeName;
		this.sampleses = sampleses;
	}

	@Id
	@Column(name = "SampleTypeId", unique = true, nullable = false)
	public int getSampleTypeId() {
		return this.sampleTypeId;
	}

	public void setSampleTypeId(int sampleTypeId) {
		this.sampleTypeId = sampleTypeId;
	}

	@Column(name = "SampleTypeName", nullable = false, length = 20)
	public String getSampleTypeName() {
		return this.sampleTypeName;
	}

	public void setSampleTypeName(String sampleTypeName) {
		this.sampleTypeName = sampleTypeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sampleTypes")
	public Set<Samples> getSampleses() {
		return this.sampleses;
	}

	public void setSampleses(Set<Samples> sampleses) {
		this.sampleses = sampleses;
	}

}
