package com.aires.model;

// Generated Jul 23, 2014 1:40:15 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Units generated by hbm2java
 */
@Entity
@Table(name = "Units", schema = "dbo", catalog = "MOBILE_AirQuality")
public class Units implements java.io.Serializable {

	private int unitId;
	private Serializable unitName;
	private Set<Chemicals> chemicalses = new HashSet<Chemicals>(0);

	public Units() {
	}

	public Units(int unitId, Serializable unitName) {
		this.unitId = unitId;
		this.unitName = unitName;
	}

	public Units(int unitId, Serializable unitName, Set<Chemicals> chemicalses) {
		this.unitId = unitId;
		this.unitName = unitName;
		this.chemicalses = chemicalses;
	}

	@Id
	@Column(name = "UnitId", unique = true, nullable = false)
	public int getUnitId() {
		return this.unitId;
	}

	public void setUnitId(int unitId) {
		this.unitId = unitId;
	}

	@Column(name = "UnitName", nullable = false)
	public Serializable getUnitName() {
		return this.unitName;
	}

	public void setUnitName(Serializable unitName) {
		this.unitName = unitName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "units")
	public Set<Chemicals> getChemicalses() {
		return this.chemicalses;
	}

	public void setChemicalses(Set<Chemicals> chemicalses) {
		this.chemicalses = chemicalses;
	}

}
