package com.aires.model;

// Generated Jul 23, 2014 1:40:15 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserProjects generated by hbm2java
 */
@Entity
@Table(name = "UserProjects", schema = "dbo", catalog = "MOBILE_AirQuality")
public class UserProjects implements java.io.Serializable {

	private int userProjectId;
	private Projects projects;
	private Users users;

	public UserProjects() {
	}

	public UserProjects(int userProjectId) {
		this.userProjectId = userProjectId;
	}

	public UserProjects(int userProjectId, Projects projects, Users users) {
		this.userProjectId = userProjectId;
		this.projects = projects;
		this.users = users;
	}

	@Id
	@Column(name = "UserProjectId", unique = true, nullable = false)
	public int getUserProjectId() {
		return this.userProjectId;
	}

	public void setUserProjectId(int userProjectId) {
		this.userProjectId = userProjectId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProjectId")
	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserId")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
