package com.aires.db.model;

// Generated Jul 23, 2014 1:40:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Certifications generated by hbm2java
 */
@Entity
@Table(name = "Certifications", schema = "dbo", catalog = "MOBILE_AirQuality")
public class Certifications implements java.io.Serializable {

	private int certificationId;
	private String certificationName;
	private Set<Users> userses = new HashSet<Users>(0);

	public Certifications() {
	}

	public Certifications(int certificationId, String certificationName) {
		this.certificationId = certificationId;
		this.certificationName = certificationName;
	}

	public Certifications(int certificationId, String certificationName,
			Set<Users> userses) {
		this.certificationId = certificationId;
		this.certificationName = certificationName;
		this.userses = userses;
	}

	@Id
	@Column(name = "CertificationId", unique = true, nullable = false)
	public int getCertificationId() {
		return this.certificationId;
	}

	public void setCertificationId(int certificationId) {
		this.certificationId = certificationId;
	}

	@Column(name = "CertificationName", nullable = false, length = 50)
	public String getCertificationName() {
		return this.certificationName;
	}

	public void setCertificationName(String certificationName) {
		this.certificationName = certificationName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "certifications")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
