package com.aires.db.model;

// Generated Jul 23, 2014 1:40:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clients generated by hbm2java
 */
@Entity
@Table(name = "Clients", schema = "dbo", catalog = "MOBILE_AirQuality")
public class Clients implements java.io.Serializable {

	private int clientId;
	private String clientName;
	private String clientCity;
	private String clientState;
	private Date createdOn;
	private Set<Projects> projectses = new HashSet<Projects>(0);
	private Set<Contacts> contactses = new HashSet<Contacts>(0);

	public Clients() {
	}

	public Clients(int clientId, String clientName, String clientCity,
			String clientState, Date createdOn) {
		this.clientId = clientId;
		this.clientName = clientName;
		this.clientCity = clientCity;
		this.clientState = clientState;
		this.createdOn = createdOn;
	}

	public Clients(int clientId, String clientName, String clientCity,
			String clientState, Date createdOn, Set<Projects> projectses,
			Set<Contacts> contactses) {
		this.clientId = clientId;
		this.clientName = clientName;
		this.clientCity = clientCity;
		this.clientState = clientState;
		this.createdOn = createdOn;
		this.projectses = projectses;
		this.contactses = contactses;
	}

	@Id
	@Column(name = "ClientId", unique = true, nullable = false)
	public int getClientId() {
		return this.clientId;
	}

	public void setClientId(int clientId) {
		this.clientId = clientId;
	}

	@Column(name = "ClientName", nullable = false, length = 100)
	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	@Column(name = "ClientCity", nullable = false, length = 100)
	public String getClientCity() {
		return this.clientCity;
	}

	public void setClientCity(String clientCity) {
		this.clientCity = clientCity;
	}

	@Column(name = "ClientState", nullable = false, length = 50)
	public String getClientState() {
		return this.clientState;
	}

	public void setClientState(String clientState) {
		this.clientState = clientState;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clients")
	public Set<Projects> getProjectses() {
		return this.projectses;
	}

	public void setProjectses(Set<Projects> projectses) {
		this.projectses = projectses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clients")
	public Set<Contacts> getContactses() {
		return this.contactses;
	}

	public void setContactses(Set<Contacts> contactses) {
		this.contactses = contactses;
	}

}
