package com.aires.db.model;

// Generated Jul 23, 2014 1:40:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DeviceTypes generated by hbm2java
 */
@Entity
@Table(name = "DeviceTypes", schema = "dbo", catalog = "MOBILE_AirQuality")
public class DeviceTypes implements java.io.Serializable {

	private int deviceTypeId;
	private String typeName;
	private Set<Samples> sampleses = new HashSet<Samples>(0);

	public DeviceTypes() {
	}

	public DeviceTypes(int deviceTypeId, String typeName) {
		this.deviceTypeId = deviceTypeId;
		this.typeName = typeName;
	}

	public DeviceTypes(int deviceTypeId, String typeName, Set<Samples> sampleses) {
		this.deviceTypeId = deviceTypeId;
		this.typeName = typeName;
		this.sampleses = sampleses;
	}

	@Id
	@Column(name = "DeviceTypeId", unique = true, nullable = false)
	public int getDeviceTypeId() {
		return this.deviceTypeId;
	}

	public void setDeviceTypeId(int deviceTypeId) {
		this.deviceTypeId = deviceTypeId;
	}

	@Column(name = "TypeName", nullable = false, length = 50)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceTypes")
	public Set<Samples> getSampleses() {
		return this.sampleses;
	}

	public void setSampleses(Set<Samples> sampleses) {
		this.sampleses = sampleses;
	}

}
