package com.aires.db.model;

// Generated Jul 23, 2014 1:40:15 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LabReportRecipients generated by hbm2java
 */
@Entity
@Table(name = "LabReportRecipients", schema = "dbo", catalog = "MOBILE_AirQuality")
public class LabReportRecipients implements java.io.Serializable {

	private int labReportRecipientId;
	private Labs labs;
	private String firstName;
	private String lastName;
	private String email;

	public LabReportRecipients() {
	}

	public LabReportRecipients(int labReportRecipientId, Labs labs,
			String firstName, String lastName, String email) {
		this.labReportRecipientId = labReportRecipientId;
		this.labs = labs;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
	}

	@Id
	@Column(name = "LabReportRecipientId", unique = true, nullable = false)
	public int getLabReportRecipientId() {
		return this.labReportRecipientId;
	}

	public void setLabReportRecipientId(int labReportRecipientId) {
		this.labReportRecipientId = labReportRecipientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LabId", nullable = false)
	public Labs getLabs() {
		return this.labs;
	}

	public void setLabs(Labs labs) {
		this.labs = labs;
	}

	@Column(name = "FirstName", nullable = false, length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LastName", nullable = false, length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "Email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
