package com.aires.db.model;

// Generated Jul 23, 2014 1:40:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Labs generated by hbm2java
 */
@Entity
@Table(name = "Labs", schema = "dbo", catalog = "MOBILE_AirQuality")
public class Labs implements java.io.Serializable {

	private int labId;
	private String labName;
	private String labEmail;
	private Date createdOn;
	private Set<LabReportRecipients> labReportRecipientses = new HashSet<LabReportRecipients>(
			0);
	private Set<Projects> projectses = new HashSet<Projects>(0);

	public Labs() {
	}

	public Labs(int labId, Date createdOn) {
		this.labId = labId;
		this.createdOn = createdOn;
	}

	public Labs(int labId, String labName, String labEmail, Date createdOn,
			Set<LabReportRecipients> labReportRecipientses,
			Set<Projects> projectses) {
		this.labId = labId;
		this.labName = labName;
		this.labEmail = labEmail;
		this.createdOn = createdOn;
		this.labReportRecipientses = labReportRecipientses;
		this.projectses = projectses;
	}

	@Id
	@Column(name = "LabId", unique = true, nullable = false)
	public int getLabId() {
		return this.labId;
	}

	public void setLabId(int labId) {
		this.labId = labId;
	}

	@Column(name = "LabName", length = 50)
	public String getLabName() {
		return this.labName;
	}

	public void setLabName(String labName) {
		this.labName = labName;
	}

	@Column(name = "LabEmail", length = 100)
	public String getLabEmail() {
		return this.labEmail;
	}

	public void setLabEmail(String labEmail) {
		this.labEmail = labEmail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "labs")
	public Set<LabReportRecipients> getLabReportRecipientses() {
		return this.labReportRecipientses;
	}

	public void setLabReportRecipientses(
			Set<LabReportRecipients> labReportRecipientses) {
		this.labReportRecipientses = labReportRecipientses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "labs")
	public Set<Projects> getProjectses() {
		return this.projectses;
	}

	public void setProjectses(Set<Projects> projectses) {
		this.projectses = projectses;
	}

}
