package com.aires.db.model;

// Generated Jul 23, 2014 1:40:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserLogin generated by hbm2java
 */
@Entity
@Table(name = "UserLogin", schema = "dbo", catalog = "MOBILE_AirQuality")
public class UserLogin implements java.io.Serializable {

	private String userName;
	private Users users;
	private String accessToken;
	private Date loginDateTime;

	public UserLogin() {
	}

	public UserLogin(String userName, Users users) {
		this.userName = userName;
		this.users = users;
	}

	public UserLogin(String userName, Users users, String accessToken,
			Date loginDateTime) {
		this.userName = userName;
		this.users = users;
		this.accessToken = accessToken;
		this.loginDateTime = loginDateTime;
	}

	@Id
	@Column(name = "UserName", unique = true, nullable = false, length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserId", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "AccessToken")
	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LoginDateTime", length = 23)
	public Date getLoginDateTime() {
		return this.loginDateTime;
	}

	public void setLoginDateTime(Date loginDateTime) {
		this.loginDateTime = loginDateTime;
	}

}
